include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/injection.config.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"

  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
