name: flutter_firebase_ddd_notes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.8.9
  freezed_annotation: ^0.7.1
  flutter_bloc: ^4.0.0

dev_dependencies:
  build_runner: ^1.8.1
  freezed: ^0.10.6

flutter:
  uses-material-design: true
