name: flutter_firebase_ddd_notes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0
  flutter_bloc: ^4.0.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  injectable: ^0.4.0+1
  get_it: ^4.0.2
  flushbar: ^1.10.4
  uuid: ^2.1.0
  auto_route: ^0.5.0
  kt_dart: ^0.7.0+1

dev_dependencies:
  build_runner: ^1.10.0
  freezed: ^0.11.2
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.5.0
  lint: ^1.2.0

flutter:
  uses-material-design: true
