name: flutter_firebase_ddd_notes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  flutter_bloc: ^4.0.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.6

dev_dependencies:
  build_runner: ^1.9.0
  freezed: ^0.10.8

flutter:
  uses-material-design: true
